use_frameworks!

platform :ios, '9.0'

target 'MKModuleManager_Example' do
  pod 'MKModuleManager', :path => '../'

  target 'MKModuleManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
